baseURL = 'https://cpuonfire.com/'
languageCode = 'en-us'
title = 'Phanis Blog'
theme = 'console'
[params]
custom_js = ["/oneko.js"]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"
  
  [[params.navlinks]]
  name = "photos/"
  url = "photos/"
  
  [[params.navlinks]]
  name = "FOSS Weekly"
  url = "https://fossweekly.beehiiv.com/"
